Surname=input()
Name=input()
Date_of_birth=input()
result=Surname+"_"+Name+"_"+Date_of_birth
print(result)
Date_of_birth=int(Date_of_birth)+60
Date_of_birth=str(Date_of_birth)
result2=Name+"_"+Surname+"_"+Date_of_birth
print(result2)
